
[build]
  publish = "."

[[redirects]]
  from = "/google15f36a4accb20436.html"
  to = "/google15f36a4accb20436.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Note: Remember to set your API_KEY in the Netlify UI:
# Site Settings > Build & deploy > Environment variables
